collections:
- name: ansible-posix-1.4.0.tar.gz
  version: 1.4.0
- name: nginxinc-nginx_core-0.7.0.tar.gz
  version: 0.7.0
- name: community-general-5.5.0.tar.gz
  version: 5.5.0
- name: community-crypto-2.9.0.tar.gz
  version: 2.9.0
