kubernetes:
  hosts:
    thor:
      ansible_user: rwittman
      ansible_host: 192.168.1.188
    ares:
      ansible_user: rwittman
      ansible_host: 192.168.1.177
    apollo:
      ansible_user: rwittman
      ansible_host: 192.168.1.213

haproxy:
  hosts:
    haproxy:
      ansible_user: rwittman
      ansible_host: 192.168.1.131