---
- name: Configure IPTables
  hosts: all
  become: true
  tasks:
    - name: Flush existing firewall rules
      ansible.builtin.iptables:
        flush: true

    - name: Firewall rule - allow all loopback traffic
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Firewall rule - allow established connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Firewall rule - allow port ping traffic
      ansible.builtin.iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: icmp

    - name: Firewall rule - allow port 22/SSH traffic
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: 22
        jump: ACCEPT
        protocol: tcp

    - name: Firewall rule - allow port 80/HTTP traffic
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: 80
        jump: ACCEPT
        protocol: tcp

    - name: Firewall rule - allow port 443/HTTPS traffic
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: 443
        jump: ACCEPT
        protocol: tcp

    - name: Firewall rule - drop any traffic without rule
      ansible.builtin.iptables:
        chain: INPUT
        jump: DROP

    - name: Install `netfilter-persistent` && `iptables-persistent` packages
      package:
        name: "{{item}}"
        state: present
      with_items:
        - iptables-persistent
        - netfilter-persistent
      when: ansible_os_family == "Debian"

    - name: Install the `fail2ban` package
      package:
        name: fail2ban
        state: latest

    - name: Override some basic fail2ban configurations
      copy:
        src: ../templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644